### PR TITLE
Refactoring test: Simple loop for `prepare_spectra()` assignments

### PR DESCRIPTION
**Pull request by philipp-baumann**
instead of `Reduce`.  @ThomasKnecht I did a bit of refactoring. The `Reduce` approach you introduced leads to very elegant, functional code in `parse_opus()`. The nested loop on the other hand makes it possible to simplify the code in  `prepare_spectra()`, and makes the assignment logic very clear in the loop. There is sure pros and cons with each of the approaches. Let me do a benchmark on more files to read, and then let's discuss. Curious about your opinion.

### CODE REVIEW

**Comment by philipp-baumann** [comment]
Current main branch:

```r
r$> # Set up -----------------------------------------------------------------------
 
    library("opusreader2")

r$> path <- file.path("data", "spectra", "2018-NABO")
    opus_files <- list.files(
      path = path, pattern = "\\.\\d+$", full.names = TRUE, recursive = TRUE
    )
    # number of OPUS files
    length(opus_files)
[1] 1612

r$> bnch_seq <- bench::mark(
      data <- opusreader2::read_opus(dsn = path)
    )
Warning message:
Some expressions had a GC in every iteration; so filtering is disabled. 

r$> bnch_seq
# A tibble: 1 × 13
  expression                                      min  median itr/s…¹ mem_a…² gc/se…³ n_itr  n_gc total…⁴
  <bch:expr>                                 <bch:tm> <bch:t>   <dbl> <bch:b>   <dbl> <int> <dbl> <bch:t>
1 data <- opusreader2::read_opus(dsn = path)    20.9s   20.9s  0.0478  8.32GB    5.02     1   105   20.9s
# … with 4 more variables: result <list>, memory <list>, time <list>, gc <list>, and abbreviated
#   variable names ¹​`itr/sec`, ²​mem_alloc, ³​`gc/sec`, ⁴​total_time
# ℹ Use `colnames()` to see all variable names
```

**Comment by philipp-baumann** [comment]
Take home:
- Speed and memory: on par
- Proposed criterion: code readability and simplicity/style

**Comment by ThomasKnecht** [comment]
i just don't like loops 😜. 
but fine with me. as i understand i right, it does not make a difference in speed and memory?

**Comment by philipp-baumann** [comment]
> i just don't like for-loops stuck_out_tongue_winking_eye. but fine with me. as i understand i right, it does not make a difference in speed and memory?

There is indeed no difference in time and memory, I am sure `Reduce` has received quite some care in that direction. Let's just drop this PR and keep in mind the take home. Though a small simplification, we don't need

https://github.com/spectral-cockpit/opusreader2/blob/c3e4c2d38594574f38de48283e6e181ddfda8dfb/R/prepare_spectra.R#L7

and we can directly assign by element name here

https://github.com/spectral-cockpit/opusreader2/blob/c3e4c2d38594574f38de48283e6e181ddfda8dfb/R/prepare_spectra.R#L32

**Comment by philipp-baumann** [comment]
> i just don't like for-loops stuck_out_tongue_winking_eye. but fine with me. as i understand i right, it does not make a difference in speed and memory?

There is indeed no difference in time and memory, I am sure `Reduce` has received quite some care in that direction. Let's just drop this PR and keep what we have learned from it.

**Pull request closed without merging**
