### PR TITLE
Bring new class attributes to `read_opus()` output list

### PR DESCRIPTION
**Pull request by philipp-baumann**
#68

### CODE REVIEW

**Comment by philipp-baumann** [comment]
shortping @ThomasKnecht (if available) cc @henningte

**Comment by henningte** [comment]
I have one general suggestion you might consider:

Both classes oerwrite the `list` class attribute. Since the `list` class has not many methods, this has no big disadvantage from the perspective of method inhritance. However, you might consider only preprending the new class attribute to the `list` class attribute: 

````
return(structure(dataset_list, class = c("list2_opusreader2", class(dataset_list))))
````

This would make it easier for users to see that the class builds on top of a list. In addition, I think it wouldn't have any disadvantage.

The same applies to other classes, such as `parameter`.

**Comment by philipp-baumann** [comment]
> I have one general suggestion you might consider:
> 
> Both classes oerwrite the `list` class attribute. Since the `list` class has not many methods, this has no big disadvantage from the perspective of method inhritance. However, you might consider only preprending the new class attribute to the `list` class attribute:
> 
> ```
> return(structure(dataset_list, class = c("list2_opusreader2", class(dataset_list))))
> ```
> 
> This would make it easier for users to see that the class builds on top of a list. In addition, I think it wouldn't have any disadvantage.
> 
> The same applies to other classes, such as `parameter`.

thanks, very good point!

**Comment by philipp-baumann** [comment]
@henningte @ThomasKnecht will introduce the reduced exports in a new feature branch

**Comment by philipp-baumann** [comment]
We should now have all that is discussed :-) thank for a final review in case you have time after hiking @ThomasKnecht . And thanks a lot for the useful hints and questions @henningte !

**Comment by henningte** [comment]
Looks good!

**Comment by philipp-baumann** [comment]
- introduce type-stable class for `read_opus()` and `read_opus_single()` output.

**Pull request merged**
