### PR TITLE
New key-value mapping to simplify header decoding (& fix CI code check)

### PR DESCRIPTION
**Pull request by philipp-baumann**
addresses #60

### CODE REVIEW

**Comment by philipp-baumann** [comment]
promt-create-dataset

**Comment by philipp-baumann** [comment]
We now gracefully encourage support :-)

stop-proactively-header-mapping

**Comment by philipp-baumann** [comment]
@ThomasKnecht have tested the new key-map logic for all internal test files. We are successful on all, except the new FT-IR remote sensing device.

**Comment by philipp-baumann** [comment]
Currently there is no other workaround than relying on classical pre-commit action instead of bot-like auto-fixing PRs via pre-commit-ci-lite => see also https://github.com/pre-commit-ci/issues/issues/13 and https://github.com/lorenzwalthert/precommit/issues/450

**Comment by philipp-baumann** [comment]
@ThomasKnecht FYI current main is now merged. CI runs now there, but just not yet in this PR. Locally this PR branch passes :100:

 
2022-12-24_01-06_pre-commit-run-all

**Comment by philipp-baumann** [comment]
FYI I have pushed some more docs into main directly. Now mostly finished with describing return value (parsed and returned OPUS blocks. => see also https://spectral-cockpit.github.io/opusreader2/reference/parse_opus.html . Once this PR is merged I, I would 

a) complete the docs of `parse_opus()` and transfer the description of output list to `read_opus()`.  

Then b) Also add support for the FT-IR remote sensing device for greenhouse gas measurements (new block types `create_dataset()`).

c)  I'd add also some more nice parameter names for Bruker Tango (We cannot yet read all of the report fields from the OPUS QUANT2 module https://www.bruker.com/en/products-and-solutions/infrared-and-raman/opus-spectroscopy-software/quantification.html ; not super important (do own modeling and infrastructure anyways) but I vaguely remember you might have once expanded the header parsing algorithm right ;-)?). 

=> Finally, my suggestion is that we bump from currently "dev" 0.0.0.9002 to to version 0.1.0 using "minor" and make a release on GH. @ThomasKnecht anything else to? Does that sound good to you?

**Review by ThomasKnecht — APPROVED** [review]

**Pull request merged**
